model:
  embedding_size: 300
  hidden_size: 10
  num_layers: 5
  dropout: 0.01
  learning_rate: 0.001

trainer:
  max_epochs: 20

datamodule:
  fit_doc_path: ../data/IMDB_reviews
  tokenizer: basic_english
  batch_size: 32
  num_workers: 0
  train_split: 0.8
  stopword_language: english
  vad_lexicon_file: ../data/lexicons/NRC-VAD-Lexicon.txt
  glove_lexicon_file: ../data/lexicons/glove.6B.300d_l2.pickle

valence_only: True
